/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package alluxio.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-05-10")
public class MountPairInfo implements org.apache.thrift.TBase<MountPairInfo, MountPairInfo._Fields>, java.io.Serializable, Cloneable, Comparable<MountPairInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MountPairInfo");

  private static final org.apache.thrift.protocol.TField ALLUXIO_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("alluxioPath", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField UFS_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("ufsPath", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MountPairInfoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MountPairInfoTupleSchemeFactory());
  }

  public String alluxioPath; // required
  public String ufsPath; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ALLUXIO_PATH((short)1, "alluxioPath"),
    UFS_PATH((short)2, "ufsPath");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ALLUXIO_PATH
          return ALLUXIO_PATH;
        case 2: // UFS_PATH
          return UFS_PATH;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ALLUXIO_PATH, new org.apache.thrift.meta_data.FieldMetaData("alluxioPath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.UFS_PATH, new org.apache.thrift.meta_data.FieldMetaData("ufsPath", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MountPairInfo.class, metaDataMap);
  }

  public MountPairInfo() {
  }

  public MountPairInfo(
    String alluxioPath,
    String ufsPath)
  {
    this();
    this.alluxioPath = alluxioPath;
    this.ufsPath = ufsPath;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MountPairInfo(MountPairInfo other) {
    if (other.isSetAlluxioPath()) {
      this.alluxioPath = other.alluxioPath;
    }
    if (other.isSetUfsPath()) {
      this.ufsPath = other.ufsPath;
    }
  }

  public MountPairInfo deepCopy() {
    return new MountPairInfo(this);
  }

  @Override
  public void clear() {
    this.alluxioPath = null;
    this.ufsPath = null;
  }

  public String getAlluxioPath() {
    return this.alluxioPath;
  }

  public MountPairInfo setAlluxioPath(String alluxioPath) {
    this.alluxioPath = alluxioPath;
    return this;
  }

  public void unsetAlluxioPath() {
    this.alluxioPath = null;
  }

  /** Returns true if field alluxioPath is set (has been assigned a value) and false otherwise */
  public boolean isSetAlluxioPath() {
    return this.alluxioPath != null;
  }

  public void setAlluxioPathIsSet(boolean value) {
    if (!value) {
      this.alluxioPath = null;
    }
  }

  public String getUfsPath() {
    return this.ufsPath;
  }

  public MountPairInfo setUfsPath(String ufsPath) {
    this.ufsPath = ufsPath;
    return this;
  }

  public void unsetUfsPath() {
    this.ufsPath = null;
  }

  /** Returns true if field ufsPath is set (has been assigned a value) and false otherwise */
  public boolean isSetUfsPath() {
    return this.ufsPath != null;
  }

  public void setUfsPathIsSet(boolean value) {
    if (!value) {
      this.ufsPath = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ALLUXIO_PATH:
      if (value == null) {
        unsetAlluxioPath();
      } else {
        setAlluxioPath((String)value);
      }
      break;

    case UFS_PATH:
      if (value == null) {
        unsetUfsPath();
      } else {
        setUfsPath((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ALLUXIO_PATH:
      return getAlluxioPath();

    case UFS_PATH:
      return getUfsPath();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ALLUXIO_PATH:
      return isSetAlluxioPath();
    case UFS_PATH:
      return isSetUfsPath();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MountPairInfo)
      return this.equals((MountPairInfo)that);
    return false;
  }

  public boolean equals(MountPairInfo that) {
    if (that == null)
      return false;

    boolean this_present_alluxioPath = true && this.isSetAlluxioPath();
    boolean that_present_alluxioPath = true && that.isSetAlluxioPath();
    if (this_present_alluxioPath || that_present_alluxioPath) {
      if (!(this_present_alluxioPath && that_present_alluxioPath))
        return false;
      if (!this.alluxioPath.equals(that.alluxioPath))
        return false;
    }

    boolean this_present_ufsPath = true && this.isSetUfsPath();
    boolean that_present_ufsPath = true && that.isSetUfsPath();
    if (this_present_ufsPath || that_present_ufsPath) {
      if (!(this_present_ufsPath && that_present_ufsPath))
        return false;
      if (!this.ufsPath.equals(that.ufsPath))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_alluxioPath = true && (isSetAlluxioPath());
    list.add(present_alluxioPath);
    if (present_alluxioPath)
      list.add(alluxioPath);

    boolean present_ufsPath = true && (isSetUfsPath());
    list.add(present_ufsPath);
    if (present_ufsPath)
      list.add(ufsPath);

    return list.hashCode();
  }

  @Override
  public int compareTo(MountPairInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAlluxioPath()).compareTo(other.isSetAlluxioPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAlluxioPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.alluxioPath, other.alluxioPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetUfsPath()).compareTo(other.isSetUfsPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUfsPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ufsPath, other.ufsPath);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MountPairInfo(");
    boolean first = true;

    sb.append("alluxioPath:");
    if (this.alluxioPath == null) {
      sb.append("null");
    } else {
      sb.append(this.alluxioPath);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ufsPath:");
    if (this.ufsPath == null) {
      sb.append("null");
    } else {
      sb.append(this.ufsPath);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MountPairInfoStandardSchemeFactory implements SchemeFactory {
    public MountPairInfoStandardScheme getScheme() {
      return new MountPairInfoStandardScheme();
    }
  }

  private static class MountPairInfoStandardScheme extends StandardScheme<MountPairInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MountPairInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ALLUXIO_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.alluxioPath = iprot.readString();
              struct.setAlluxioPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // UFS_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ufsPath = iprot.readString();
              struct.setUfsPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MountPairInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.alluxioPath != null) {
        oprot.writeFieldBegin(ALLUXIO_PATH_FIELD_DESC);
        oprot.writeString(struct.alluxioPath);
        oprot.writeFieldEnd();
      }
      if (struct.ufsPath != null) {
        oprot.writeFieldBegin(UFS_PATH_FIELD_DESC);
        oprot.writeString(struct.ufsPath);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MountPairInfoTupleSchemeFactory implements SchemeFactory {
    public MountPairInfoTupleScheme getScheme() {
      return new MountPairInfoTupleScheme();
    }
  }

  private static class MountPairInfoTupleScheme extends TupleScheme<MountPairInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MountPairInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetAlluxioPath()) {
        optionals.set(0);
      }
      if (struct.isSetUfsPath()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetAlluxioPath()) {
        oprot.writeString(struct.alluxioPath);
      }
      if (struct.isSetUfsPath()) {
        oprot.writeString(struct.ufsPath);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MountPairInfo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.alluxioPath = iprot.readString();
        struct.setAlluxioPathIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ufsPath = iprot.readString();
        struct.setUfsPathIsSet(true);
      }
    }
  }

}

